version: "3.8"

services:
  db:
    image: postgres:13
    container_name: viatab_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data  

  backend:
    build: ./backendV1
    container_name: viatab_backend
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://viatab_postgres:5432/postgres
    ports:
      - "8080:8080"  # Ensure the backend service exposes port 8080 to the host

  frontend:
    build:
      context: ./my-react-app
    container_name: react-app
    ports:
      - "3000:80"

volumes:
  postgres-data:  
