version: "3.8"

services:
  db:
    image: postgres:13
    container_name: viatab_postgres
    restart: always
    environment:
      POSTGRES_USER: viatab_user       # Set your desired username
      POSTGRES_PASSWORD: mysecretpassword   # Set your desired password
    volumes:
      - postgres-data:/var/lib/postgresql/data  

  backend:
    build: ./backendV1
    container_name: viatab_backend
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://viatab_postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: viatab_user
      SPRING_DATASOURCE_PASSWORD: mysecretpassword
    ports:
      - "8080:8080"
 
  frontend:
    build:
      context: ./my-react-app
    container_name: react-app
    ports:
      - "3000:80"

volumes:
  postgres-data:
