version: "3.8"

services:
  backend:
    build:
      context: ./backendV1
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/viatabdb
      - SPRING_DATASOURCE_USERNAME=viauser
      - SPRING_DATASOURCE_PASSWORD=viapass
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13-alpine
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=viatabdb
      - POSTGRES_USER=viauser
      - POSTGRES_PASSWORD=viapass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U viauser"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./my-react-app
      dockerfile: Dockerfile  
    container_name: react-app
    ports:
      - "3000:80"

volumes:
  postgres-data:
