version: '3.8'

services:
  backend:
    build: .
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      # IMPORTANT: Note the URL below uses the container name 'db'
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/viatabdb
      - SPRING_DATASOURCE_USERNAME=viauser
      - SPRING_DATASOURCE_PASSWORD=viapass
      # You can add additional Spring Boot properties if needed
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=viatabdb
      - POSTGRES_USER=viauser
      - POSTGRES_PASSWORD=viapass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
